config/routes.rb
SimpleBlog::Application.routes.draw do
  get "password_resets/new"

  get "signup" => "users#new", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"  
  get "login" => "sessions#new", :as => "login"  
  resources :users
  resources :password_resets
  resources :sessions
  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
  validate :post, presence: true

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :content, :title, presence: true
  validates :content, length: { maximum: 5000} 
  validates :title, length: { maximum: 100} 

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :password, :password_confirmation

  before_create { generate_token(:auth_token) }
  before_save :encrypt_password

  validates :email, presence: true, uniqueness: true
  validates :password, on: :create, confirmation: true
  #validates :email, format: { with: /^.+$/}

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def encrypt_password
	  	if password.present?
  		  self.password_salt = BCrypt::Engine.generate_salt()
  		  self.password_hash = BCrypt::Engine.hash_secret(password, self.password_salt)
	    end
  end

  def authenticate(password)
  	if self.password_hash == BCrypt::Engine.hash_secret(password, self.password_salt) 
  		self
	  else
  		nil
  	end
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create 
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment])
		redirect_to post_path(@post)
	end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	user.send_password_reset if user
  	redirect_to root_url, :notice => "Email sent with password reset instructions."
  end



  def edit
  	@user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at > 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired"
    elsif  @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset"
    else
      render :edit
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])    
    @post.update_attributes(params[:post])
    if @post.valid?
      render :show 
    else
      render "edit"
    end
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.create(params[:post])
  	if @post.valid?
  		redirect_to posts_path
  	else
  		render "new"
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end



  def create
    user = User.find_by_email(params[:email])
   	if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end

  		redirect_to root_url, notice: "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end
  end


  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  			
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>


</div>
</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Password Reset</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>

	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do | msg | %>
			<div class="alert alert_error">
				<ul>
					<li> <%= msg %> </li>
				</ul>
			</div>
		<% end %>
	<% end %>
	
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>		
	</div>

	<div>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>		
	</div>	

	<div class="action"> <%= f.submit "Update Password" %> </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Password Reset</h1>

<%= form_tag password_resets_path, :method => :post do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email, params[:email] %>
	</div>
	<div class="actions"> <%= submit_tag "Reset Password" %></div>
<% end %>

app/views/posts/_post_form.html.erb
<%= render "shared/errors" %>

<%= form_for @post  do |f| %>
	<div>
	<%= f.label "Title:"%> <p>
	<%= f.text_field :title %>
	</div>
	<div>
	<%= f.label "Content:" %><p>
	<%= f.text_area :content %>	
	</div>
	<div>
	<%= f.submit "Submit", class: "btn" %>
	<%= link_to "Cancel", @post, class: "btn" %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
<div class="span6 offset4">
<h1>Edit Post</h1>
<div class="well">
<%= render "post_form" %>
</div>
</div>
</div>

app/views/posts/index.html.erb
<div class="row">
	<div class="span8 offset2">
		<h1 id="blogtitle">Super Blog</h1>		
	</div>
</div>
<div class="row">
	<div class="span8 offset2">
		<%= "No posts" unless @posts.any? %>
		<%  @posts.each do |post| %>
			<div class="well">
			<h2> <%= link_to post.title, post_path(post) %></h2>
			<p> <%= post.content %> </p>
			</div>
		<% end %>
	</div>

<div class="span2 well">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

  	<% if current_user %>
  		Logged in as <%= current_user.email %>  | <%= link_to "Logout", logout_path %>
  		<p/>
  	<% else %>
		<%= link_to "Sign-up", "signup" %> |	<%= link_to "Login", "login" %>  		
  	<% end %>
	
	<%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

app/views/posts/show.html.erb
<div class="row">
	<div class="span8 offset2">
		<h1 id="blogtitle">Super Blog</h1>	
		<%= link_to "Back to main blog", posts_path	%>
	</div>
</div>
<div class="row">
	<div class="span8 offset2">
	<div class="well">
		<h2> <%= @post.title %></h2>
		<em> Posted on <%= @post.created_at %></em>
		<p><%= link_to "Edit post", edit_post_path(@post) %></p>
		<p> </p>
		<p> <%= @post.content %> </p>
		<p/>

		<% if @post.comments.size > 0 %>	<h3>Comments</h3>	<% end %>

		<% @post.comments.all.each  do |comment| %>
			<div class="well"> 
				<p> <em> Comment posted by XXX on <%= comment.updated_at %> </em> </p>
				<p> <%= comment.body %>  </p>
			</div>
		<% end %>

		<h2>Post a comment</h2>
		<%= form_for([@post, @post.comments.build]) do |f| %>
			<div class="field"> 
				<%= f.text_area :body %> 
			</div>
			<div>
				<%= f.submit "Create Comments" %>
			</div>
		<% end %>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do | msg | %>
		<div class="alert alert_error">
		<ul>
			<li> <%= msg %> </li>
		</ul>
		</div>
	<% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign-up<h2>



<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
	<div>
	<%= f.label "Email:"%> <p>
	<%= f.text_field :email %>
	</div>
	<div>
	<%= f.label "Password:" %><p>
	<%= f.password_field :password %>	
	</div>
	<div>
	<%= f.label "Password Confirmation:" %><p>
	<%= f.password_field :password_confirmation %>	
	</div>
	<div>
	<%= f.submit "Submit", class: "btn" %>

<% end %>